import type { Metadata } from "next";
import LeftSidebar from "@/app/ui/left-sidebar";
import Header from "@/app/ui/header";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background-tone1 antialiased min-h-screen`}
      >
        <div className="flex flex-col min-h-screen">
          <Header />
          <div className="flex flex-row min-h-screen w-full">
            <LeftSidebar />
            <div className="w-full rounded bg-background">
              {children}
            </div>
          </div>
        </div>

      </body>
    </html>
  );
}
